# Generated by Django 4.0.6 on 2022-09-29 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableInfo',
            fields=[
                ('tbl_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('db_schema', models.CharField(max_length=64)),
                ('tbl_nm', models.CharField(max_length=128)),
                ('tbl_kor_nm', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'meta"."tbl_item_bas',
                'unique_together': {('db_schema', 'tbl_nm')},
            },
        ),
        migrations.CreateModel(
            name='ColumnInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_nm', models.CharField(max_length=128)),
                ('eng_nm', models.CharField(max_length=128)),
                ('data_type', models.CharField(max_length=32)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.tableinfo')),
            ],
            options={
                'db_table': 'meta"."tbl_item_coln_dtl',
            },
        ),
    ]
