# Generated by Django 4.0.6 on 2022-08-16 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableInfo',
            fields=[
                ('table_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('schema', models.CharField(max_length=64)),
                ('table_nm', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'meta"."tb_table_list',
                'unique_together': {('schema', 'table_nm')},
            },
        ),
        migrations.CreateModel(
            name='ColumnInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_nm', models.CharField(max_length=128)),
                ('eng_nm', models.CharField(max_length=128)),
                ('data_type', models.CharField(max_length=32)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.tableinfo')),
            ],
            options={
                'db_table': 'meta"."tb_table_column_info',
            },
        ),
    ]
