# Generated by Django 4.0.6 on 2022-09-29 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='columninfo',
            old_name='table',
            new_name='tbl_id',
        ),
    ]
