# Generated by Django 4.0.6 on 2022-09-29 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_rename_table_columninfo_tbl_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columninfo',
            name='tbl_id',
            field=models.ForeignKey(db_column='tbl_id', on_delete=django.db.models.deletion.CASCADE, to='table.tableinfo'),
        ),
    ]
