# Generated by Django 3.1.3 on 2022-08-02 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='ctgry',
            field=models.ForeignKey(db_column='ctgry', on_delete=django.db.models.deletion.PROTECT, to='api.serverinfo'),
        ),
        migrations.AlterField(
            model_name='apiparaminfo',
            name='api_nm',
            field=models.ForeignKey(db_column='api_nm', on_delete=django.db.models.deletion.CASCADE, to='api.apiinfo'),
        ),
    ]
