# Generated by Django 4.0.6 on 2022-08-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220803_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='meth',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
