# Generated by Django 4.0.6 on 2022-08-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_apiinfo_meth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
