# Generated by Django 4.0.6 on 2022-08-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_apiinfo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='meth',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
