    """
        [
            {
                "method":"INSERT",
                "table_nm":"inqr_bas",
                "data":{
                    "id":"9bb29b2b-159e-4cee-89af-a80cfe6f0651",
                    "title":"test문의",
                    "sbst":"문으으으의",
                    "ctg_id":"INQR001",
                    "reg_user_nm":"테스터",
                    "cmpno":"dev-12346578",
                    "del_yn":"N",
                    "reg_user":"f142cdc2-207b-4eda-9e7d-2605e4e65571",
                    "reg_date":"NOW()",
                    "amd_user":"f142cdc2-207b-4eda-9e7d-2605e4e65571",
                    "amd_date":"NOW()"
                }
            }
        ]
        {"result":1,"errorMessage":""}
    """